version: "2"
services:
  sqs:
    container_name: sqs
    image: roribio16/alpine-sqs:latest
    volumes:
      - ./sqs.conf:/opt/custom/elasticmq.conf
    ports:
      - "9324:9324"
      - "9325:9325" # Web interface
