service: cvs-svc-retro-gen-init

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev

plugins:
  - serverless-plugin-typescript

functions:
  main:
    handler: src/handler.handler
    events:
      - stream:
          batchSize: 100
          startingPosition: LATEST
          enabled: true