service: cvs-svc-retro-gen-init

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  tracing: true # enable tracing
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-tracing

functions:
  main:
    handler: src/handler.handler
    events:
      - stream:
          batchSize: 100
          startingPosition: LATEST
          enabled: true
