service: cvs-svc-retro-gen-init
configValidationMode: warn
provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  stage: dev
  tracing:
    lambda: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-tracing

functions:
  main:
    handler: src/handler.handler
    events:
      - stream:
          batchSize: 100
          startingPosition: LATEST
          enabled: true
